on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
env:
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
permissions:
  contents: write
jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 25
          cache: gradle
      - uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: current
      - run: |
          gradle clean openApiGenerate spotlessApply
          git add -f build/generate-resources/main/src/main/java
          if git diff --cached --quiet
          then
            echo No changes to commit
          else
            git commit -m 'chore: automated periodic openapi generation'
            git push
          fi
